version: 0.2

phases:
  pre_build:
    commands:
      - make login-ecr
  build:
    commands:
      - make build
  post_build:
    commands:
      - make publish
      - make write-image-definitions
artifacts:
    files: imagedefinitions.json