AWSTemplateFormatVersion: 2010-09-09
Description: The CodeDeploy Pipeline with Artifacts Store and ECR Repository
Parameters: 
  ECRRepositoryName:
    Type: String
    Description: "The Name of ECR Repository"
Resources: 
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref 'ECRRepositoryName'
  ECRBuildRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Join ['-', [!Ref 'ECRRepositoryName', 'build']]
Outputs:
  ECRRepository:
    Description: "The Name of ECR Repository"
    Value: !Ref ECRRepository
  ECRBuildRepository:
    Description: "The Name of ECR Repository for Build Image"
    Value: !Ref ECRBuildRepository
